language: node_js

node_js:
- '8'
- '9'
- '10'

script:
- npm run test

env:
- CXX=g++-4.8


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 4cee2f60edbf31acac6ddff823f0b93e2e9882c3e5c55130049e0fd878549f84

after_success:
- npm run coveralls
